"""Real causal contexts and frozen fills for PAPER weighted target economics.

Synthetic native bars are generated by the structural engine's fixture. These
checks establish accounting/provenance correctness, not strategy profitability.
"""
from copy import deepcopy
from datetime import datetime, timedelta, timezone
import unittest

import veritas_canonical_constitution as CTC
import veritas_costs as VC
import veritas_execution as VX
import veritas_execution_snapshot as VES
import veritas_stop_risk as VSR
import veritas_structural_breakout as SB
import veritas_timeframe_policy as TFP
from test_veritas_structural_breakout import raw_at, bars, CLOSES, POLICY


def structural_plan(direction='LONG', price=103.8, width=1., one_target=False, now=None):
    hourly = bars([min(106, p) for p in CLOSES], '1h') if one_target else None
    raw, clock = raw_at(price=price, at=now, hourly=hourly)
    # Affine compression preserves causal levels and time; reflection exercises SHORT.
    def convert(value):
        value = 100. + width * (value - 100.)
        return value if direction == 'LONG' else 220. - value
    for native in raw['structure_bars_by_timeframe'].values():
        for bar in native:
            old = dict(bar)
            for key in ('open', 'close'):
                bar[key] = convert(old[key])
            bar['high'] = convert(old['high' if direction == 'LONG' else 'low'])
            bar['low'] = convert(old['low' if direction == 'LONG' else 'high'])
    old_bid, old_ask = raw['best_bid'], raw['best_ask']
    raw.update(price=convert(raw['price']),
               best_bid=convert(old_bid if direction == 'LONG' else old_ask),
               best_ask=convert(old_ask if direction == 'LONG' else old_bid))
    context = SB.build_context(raw, '1h', clock, config=POLICY)
    event = context['event']
    geometry = SB.entry_gate(context, raw['price'], direction, clock)
    if not geometry['eligible']:
        raise AssertionError(geometry)
    plan = dict(direction=direction, horizon='1h', entry_price=raw['price'],
        stop_price=event['stop_price'], target_price=event['target_price'],
        runner_target_price=event['runner_target_price'], target_ladder=deepcopy(event['target_ladder']),
        timeframe_entry_context=context, structural_policy_version=CTC.BREAKOUT_LIFECYCLE_POLICY['version'],
        expected_move_pct=geometry['remaining_move_pct'], expected_to_stop_ratio=geometry['reward_risk'],
        expected_hold_seconds=3600., initial_position_fraction=.5,
        best_bid=raw['best_bid'], best_ask=raw['best_ask'], market_observed_at=raw['observed_at'])
    return raw, clock, plan


class WeightedStructuralEconomicsTests(unittest.TestCase):
    def test_repriced_quote_replaces_or_clears_book_as_one_snapshot(self):
        raw, clock, plan = structural_plan()
        for aliases in (False, True):
            quote = deepcopy(raw)
            quote['observed_at'] = (clock+timedelta(seconds=1)).isoformat()
            bid, ask = quote.pop('best_bid'), quote.pop('best_ask')
            quote.pop('spread_bps',None)
            if aliases:
                quote.update(bid=bid,ask=ask,spread_bps=1.)
            prior = deepcopy(plan)
            prior['spread_bps'] = 500.
            row = dict(raw,horizon='1h',research_decision='LONG',trade_plan=prior,
                       _execution_quote=quote)
            prepared = TFP.prepare_row(row,now=clock+timedelta(seconds=1))['trade_plan']
            self.assertTrue(prepared['eligible'],prepared['reason'])
            self.assertEqual(prepared['best_bid'],bid if aliases else None)
            self.assertEqual(prepared['best_ask'],ask if aliases else None)
            self.assertEqual(prepared['spread_bps'],1. if aliases else None)
            final = TFP.final_plan('CNYRUBF','LONG',prepared,clock+timedelta(seconds=1))
            self.assertTrue(final['eligible'],final['reason'])
            self.assertEqual(final['best_bid'],prepared['best_bid'])
            self.assertEqual(final['best_ask'],prepared['best_ask'])
            self.assertEqual(final['spread_bps'],prepared['spread_bps'])

    def test_incomplete_or_corrupted_event_is_a_refusal_without_exception(self):
        raw, clock, plan = structural_plan()
        original = deepcopy(plan['timeframe_entry_context']['event'])
        corrupt = deepcopy(original)
        corrupt['target_ladder'] = [{'price':'bad'}]
        for event in ({'version':SB.VERSION,'event_id':'FAKE','direction':'LONG'},corrupt):
            candidate = deepcopy(plan)
            candidate['timeframe_entry_context']['event'] = event
            row = dict(raw,horizon='1h',research_decision='LONG',trade_plan=candidate,
                       _execution_quote=deepcopy(raw))
            prepared = TFP.prepare_row(row,now=clock)['trade_plan']
            self.assertFalse(prepared['eligible'])
            self.assertEqual(prepared['entry_timing_gate']['reason'],'STRUCTURAL_EVENT_PROOF_INVALID')
            self.assertEqual(prepared['r66_geometry']['reason'],'STRUCTURAL_EVENT_PROOF_INVALID')
        self.assertEqual(plan['timeframe_entry_context']['event'],original)

    def gate(self, **options):
        raw, clock, plan = structural_plan(**options)
        return raw, clock, plan, VX.economics_gate('CNYRUBF', plan, now=clock)

    def test_low_rr_valid_context_gets_diagnostic_rr_and_full_risk_cap(self):
        for direction in ('LONG', 'SHORT'):
            raw, clock, plan, gate = self.gate(direction=direction)
            self.assertTrue(gate['eligible'], gate['blockers'])
            self.assertGreater(gate['net_reward_risk'], 0)
            self.assertLess(gate['net_reward_risk'], VX.MIN_REWARD_RISK)
            self.assertEqual(gate['minimum_reward_risk'], 0)
            self.assertTrue(VX.paper_structural_economics_validated(gate))
            self.assertEqual(gate['target_price'], plan['target_price'])
            self.assertEqual(gate['runner_target_price'], plan['runner_target_price'])
            budget = VSR.cap_fraction_from_economics(gate, 10., CTC.runtime_portfolio_policy('Currency'))
            self.assertTrue(budget['eligible'], budget)
            self.assertLessEqual(budget['total_stop_risk_nav_after'], .02)
            self.assertLess(budget['fraction'], 10.)

    def test_each_planned_exit_has_fill_fee_and_fraction_of_funding(self):
        for direction in ('LONG', 'SHORT'):
            raw, clock, plan = structural_plan(direction=direction)
            plan.update(expected_hold_seconds=3*86400., position_age_seconds=2*86400.)
            gate = VX.economics_gate('CNYRUBF', plan, now=clock)
            self.assertTrue(gate['eligible'], gate['blockers'])
            sign = 1 if direction == 'LONG' else -1
            entry = gate['modeled_entry_fill']
            fees = entry * VC.COMMISSION_RATE
            funding = entry * (VC.funding_fraction(5*86400.) - VC.funding_fraction(2*86400.))
            gross = 0.
            for rung, modeled in zip(plan['target_ladder'], gate['target_execution_models']):
                self.assertEqual(modeled['fraction'], .5)
                self.assertEqual(modeled['execution_model']['reference_price'], rung['price'])
                self.assertEqual(modeled['execution_model']['side'], 'SELL' if direction == 'LONG' else 'BUY_TO_COVER')
                fill = rung['price'] * (1.-sign*VC.SLIPPAGE_RATE)
                self.assertAlmostEqual(modeled['modeled_fill'], fill)
                self.assertAlmostEqual(modeled['exit_commission_per_unit'], .5*fill*VC.COMMISSION_RATE)
                self.assertAlmostEqual(modeled['expected_funding_per_unit'], .5*funding)
                fees += .5*fill*VC.COMMISSION_RATE
                gross += .5*sign*(fill-entry)
            self.assertAlmostEqual(gate['modeled_commission_pct'], fees/raw['price'])
            self.assertAlmostEqual(gate['net_reward_pct'], (gross-fees-funding)/entry)
            self.assertAlmostEqual(sum(x['net_reward_pct'] for x in gate['target_execution_models']), gate['net_reward_pct'])
            stop = gate['modeled_stop_fill']
            self.assertAlmostEqual(gate['net_risk_pct'],
                (sign*(entry-stop)+VC.COMMISSION_RATE*(entry+stop)+funding)/entry)
            self.assertEqual(gate['modeled_target_fill'], gate['target_execution_models'][0]['modeled_fill'])
            self.assertNotEqual(gate['modeled_target_fill'], gate['modeled_weighted_target_fill'])

    def test_one_observed_zone_is_full_exit_without_invented_second_target(self):
        raw, clock, plan, gate = self.gate(one_target=True)
        self.assertTrue(gate['eligible'], gate['blockers'])
        self.assertEqual(len(gate['target_ladder']), 1)
        self.assertEqual(gate['target_ladder'][0]['fraction'], 1.)
        self.assertEqual(gate['target_price'], gate['runner_target_price'])
        self.assertEqual(gate['modeled_target_fill'], gate['modeled_weighted_target_fill'])

    def test_move_floor_and_cost_buffer_survive_rr_policy_change(self):
        # Keep the actual modeled fill early enough for TP1. The compressed
        # historical zones leave a positive weighted reward below the move
        # floor, so this refusal must come from costs rather than entry timing.
        raw, clock, plan, gate = self.gate(price=102., width=.02)
        self.assertGreater(gate['net_reward_pct'], 0.)
        self.assertFalse(gate['eligible'])
        self.assertEqual(gate['blockers'], ['EXPECTED_MOVE_BELOW_COST_BUFFER'])
        self.assertEqual(gate['minimum_expected_move_pct'], .0019)
        # A conservative observed spread remains part of the cost-buffer ceiling.
        raw, clock, plan, gate = self.gate(price=101., width=.04)
        self.assertTrue(gate['eligible'], gate['blockers'])
        plan['spread_bps'] = 50.
        gate = VX.economics_gate('CNYRUBF', plan, now=clock)
        self.assertFalse(gate['eligible'])
        self.assertEqual(gate['blockers'], ['EXPECTED_MOVE_BELOW_COST_BUFFER'])
        self.assertGreaterEqual(gate['minimum_expected_move_pct'], .005*1.1)
        raw, clock, plan, gate = self.gate(price=100.6, width=.014)
        self.assertLess(gate['net_reward_pct'], 0.)
        self.assertIn('TARGET_NOT_PROFITABLE_AFTER_COSTS', gate['blockers'])
        self.assertFalse(any(code.startswith('STRUCTURAL_') for code in gate['blockers']))

    def test_legacy_and_live_do_not_inherit_paper_rr_waiver(self):
        raw, clock, plan, paper = self.gate()
        legacy = deepcopy(plan)
        legacy.pop('timeframe_entry_context')
        legacy.pop('structural_policy_version')
        legacy.update(minimum_reward_risk=0., economics_policy=deepcopy(paper['economics_policy']))
        for candidate, mode in ((legacy, 'PAPER'), (plan, 'LIVE')):
            gate = VX.economics_gate('CNYRUBF', candidate, execution_mode=mode, now=clock)
            self.assertFalse(gate['eligible'])
            self.assertEqual(gate['minimum_reward_risk'], VX.MIN_REWARD_RISK)
            self.assertIn('NET_REWARD_RISK_BELOW_FLOOR', gate['blockers'])
            self.assertEqual(gate['target_ladder'], [])
        # Exercise the real production boundary, with all external controls supplied.
        raw, clock, current_plan = structural_plan(now=datetime.now(timezone.utc))
        live = VX.production_order_gate('CNYRUBF', current_plan, {'eligible':True}, True, .9,
            .001, .1, .1, 0., total_open_stop_risk_nav_after=.001,
            correlated_stop_risk_nav_after=.001, instrument_spec_validated=True,
            model_promoted=True, model_version='TEST', daily_pnl_pct=0., weekly_pnl_pct=0.,
            broker_reconciled=True)
        self.assertFalse(live['eligible'])
        self.assertIn('NET_REWARD_RISK_BELOW_FLOOR', live['blockers'])

    def test_altered_or_missing_target_provenance_cannot_relax_rr(self):
        raw, clock, plan = structural_plan()
        cases = []
        p=deepcopy(plan);p['target_ladder'][1]['price']+=1;cases.append(p)
        p=deepcopy(plan);p['target_ladder'][0]['fraction']=.9;cases.append(p)
        p=deepcopy(plan);p.pop('target_ladder');cases.append(p)
        p=deepcopy(plan);p['timeframe_entry_context']['event']['target_zones'][0]['price']+=1;cases.append(p)
        p=deepcopy(plan);p['timeframe_entry_context']['source_identity']['contract_id']='OTHER';cases.append(p)
        p=deepcopy(plan);p.pop('timeframe_entry_context');cases.append(p)
        p=deepcopy(plan);p['entry_price']+=.001;cases.append(p)
        p=deepcopy(plan);p['best_ask']+=.01;cases.append(p)
        for p in cases:
            gate=VX.economics_gate('CNYRUBF',p,now=clock)
            self.assertFalse(gate['eligible'],p)
            self.assertEqual(gate['minimum_reward_risk'],VX.MIN_REWARD_RISK)

    def test_old_context_and_decision_as_of_do_not_refresh_a_current_decision(self):
        raw, clock, plan = structural_plan()
        plan['decision_as_of']=clock.isoformat()
        stale=VX.economics_gate('CNYRUBF',plan,now=clock+timedelta(minutes=5))
        self.assertFalse(stale['eligible'])
        self.assertIn('EXECUTION_QUOTE_STALE',stale['blockers'])
        self.assertFalse(VX.economics_gate('CNYRUBF',plan)['eligible'])

    def test_sizing_rejects_forged_policy_or_mutated_weighted_fills(self):
        raw, clock, plan, gate = self.gate()
        for change in ('missing_context','weight','fill','risk','live','floor'):
            altered=deepcopy(gate)
            if change=='missing_context':altered.pop('structural_economics_context')
            if change=='weight':altered['target_execution_models'][0]['fraction']=.9
            if change=='fill':altered['target_execution_models'][1]['modeled_fill']+=1
            if change=='risk':altered['net_risk_pct']/=2;altered['net_reward_risk']*=2
            if change=='live':altered['economics_policy']['execution_mode']='LIVE'
            if change=='floor':altered['minimum_reward_risk']=-1
            sized=VSR.cap_fraction_from_economics(altered,10.,CTC.runtime_portfolio_policy('Currency'))
            self.assertFalse(sized['eligible'],change)
            self.assertEqual(sized['add_fraction'],0.)

    def test_snapshot_freezes_all_ladder_models_policy_and_causal_context(self):
        raw, clock, plan, gate = self.gate()
        row=dict(raw,horizon='1h',timeframe_entry_context=plan['timeframe_entry_context'],trade_plan=plan)
        gate['entry_geometry']=SB.entry_gate(plan['timeframe_entry_context'],raw['price'],'LONG',clock)
        gate['execution_snapshot']=VES.capture(row,raw,'LONG',.5,clock,gate)
        self.assertIsNotNone(VES.checked_fill(gate,raw,'CNYRUBF','LONG',raw['price'],.5))
        for field in ('target_ladder','target_execution_models','economics_policy','structural_economics_context'):
            altered=deepcopy(gate)
            if field=='target_ladder':altered[field][1]['fraction']=.1
            if field=='target_execution_models':altered[field][0]['modeled_fill']+=1
            if field=='economics_policy':altered[field]['minimum_reward_risk']=-1
            if field=='structural_economics_context':altered[field]['quote']['price']+=1
            self.assertIsNone(VES.checked_fill(altered,raw,'CNYRUBF','LONG',raw['price'],.5),field)
        frozen=deepcopy(gate['execution_snapshot'])
        plan['target_ladder'][0]['price']+=1
        self.assertEqual(gate['execution_snapshot'],frozen)

    def test_add_reserves_held_exposure_at_effective_trailing_stop(self):
        raw, clock, plan = structural_plan()
        held=dict(direction='LONG',units=10.,stop_price=plan['stop_price'],
                  opened_at=(clock-timedelta(hours=1)).isoformat(),payload={'trailing_stop':99.})
        self.assertEqual(VSR.effective_stop_price(held),99.)
        plan['stop_price']=VSR.effective_stop_price(held)
        gate=VX.economics_gate('CNYRUBF',plan,now=clock)
        reserve=VSR.existing_stop_risk_nav(held,gate['modeled_stop_fill'],10000.,clock,
                  mark_price=raw['price'],expected_hold_seconds=gate['expected_hold_seconds'])
        self.assertTrue(reserve['eligible'],reserve)
        current=held['units']*raw['price']/10000.
        sized=VSR.cap_fraction_from_economics(gate,1.,CTC.runtime_portfolio_policy('Currency'),
                    current_fraction=current,existing_stop_risk_nav=reserve['net_stop_risk_nav'])
        self.assertTrue(sized['eligible'],sized)
        self.assertLessEqual(sized['total_stop_risk_nav_after'],.02)
        self.assertEqual(reserve['stop_price'],99.)
        self.assertAlmostEqual(sized['total_stop_risk_nav_after'],
                               reserve['net_stop_risk_nav']+sized['add_fraction']*gate['net_risk_pct'])

    def test_final_entry_and_add_keep_weighted_room_and_new_historical_ladder(self):
        raw, clock, plan = structural_plan()
        row=dict(raw,horizon='1h',research_decision='LONG',decision='LONG',
                 timeframe_entry_context=plan['timeframe_entry_context'],trade_plan=plan,
                 _execution_quote=deepcopy(raw),market_observed_at=raw['observed_at'])
        held=dict(asset='CNYRUBF',direction='LONG',units=10.,avg_entry_price=100.,
            stop_price=plan['stop_price'],opened_at=clock.isoformat(),
            payload={'trailing_stop':99.,'take_price':102.,'target_price':102.,'r17_tp1_done':True})
        original=deepcopy(held)
        for position in (None,held):
            gate=VX.entry_gate(row,raw['price'],'LONG',.2,position,
                existing_target_price=102. if position else None,now=clock,execution_fraction=.1)
            self.assertTrue(gate['eligible'],gate['blockers'])
            self.assertEqual(gate['target_ladder'],plan['target_ladder'])
            self.assertEqual(gate['target_price'],plan['target_price'])
            self.assertAlmostEqual(gate['expected_move_pct'],plan['expected_move_pct'])
            self.assertEqual(gate['stop_price'],99. if position else plan['stop_price'])
            self.assertTrue(VX.paper_structural_economics_validated(gate))
            self.assertIsNotNone(VES.checked_fill(gate,raw,'CNYRUBF','LONG',raw['price'],.1))
        self.assertEqual(held,original)


if __name__=='__main__':
    unittest.main()
