const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('veritas_v90_ui.py','utf8');
const script=source.split('<script>')[1].split('</script>')[0];
const context=vm.createContext({document:{readyState:'loading',addEventListener(){}}});
vm.runInContext(script.replace(/\}\)\(\);\s*$/, 'globalThis.sourceText=positionSourceText;})();'),context);
const label=context.sourceText;
const pf={asset:'BRENT',price_source_lock:{key:'PROFINANCE:Brent oil',primary_source:'ProFinance',contract_id:null}};
assert.match(label(pf),/ProFinance.*Brent oil.*ожидается проверка ленты/);
assert.doesNotMatch(label(pf),/BRX6|BRZ6|непрерывн/);
const feed={...pf,price_source_lock:{...pf.price_source_lock,source_pin_version:'PROFINANCE_BRENT_PIN_V1',provider_ticker:'brent',provider_instrument_id:'27'}};
assert.match(label(feed),/ProFinance.*Brent \(brent\).*источник закреплён/);
assert.doesNotMatch(label(feed),/не подтверждён|контракт 27|ожидается/);
const verified={...pf,valuation_basis:{source_key:'PROFINANCE:Brent oil',source_pin_status:'PINNED_PROVIDER_FEED',provider_ticker:'brent',provider_instrument_id:'27'}};
assert.match(label(verified),/источник закреплён/);
assert.match(label({...verified,valuation_basis:{...verified.valuation_basis,source_key:'YAHOO:BZ=F'}}),/ожидается проверка ленты/);
assert.match(label({...feed,price_source_lock:{...feed.price_source_lock,provider_instrument_id:'28'}}),/ожидается проверка ленты/);
const pinned={asset:'BRENT',price_source_lock:{key:'MOEX:BRENT',primary_source:'MOEX ISS BRX6',contract_id:'BRX6'}};
assert.match(label(pinned),/контракт BRX6/);
assert.doesNotMatch(label(pinned),/не подтверждён/);
assert.match(label({asset:'BRENT',payload:{price_source_lock:feed.price_source_lock}}),/источник закреплён/);
assert.equal(label({asset:'GOLD',price_source_lock:pf.price_source_lock}),'ProFinance');
assert.doesNotMatch(label({...pinned,price_source_lock:{primary_source:'<script>',contract_id:'<img>'}}),/<script>|<img>/);
console.log('PASS: Brent source labels require a verified feed pin, preserve exact held contracts, and escape provider text');
